version: 2
jobs:
  build:
    docker:
      - image: docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/autodeploy:$CIRCLE_SHA1 .
    steps:
      - checkout
      - run: echo "About to start deploy on ${CIRCLE_BRANCH}"
      - run: ./.circleci/setup.sh
      - deploy:
          name: Deploy Master Branch to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy/deploy.sh
            else
              echo "Skipping deploy, branch is not master"
            fi
