version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: digitalgenius/alpine-jq-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install --upgrade pip 
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76 

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/autodeploy:${CIRCLE_SHA1} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/autodeploy:${CIRCLE_SHA1}
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Configure aws credentials
          command: |
            aws configure set default.region us-west-2
            aws configure set default.output json
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sh setup.sh
            fi