version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
    steps:
      - deploy:
          name: Deploy Master to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash .circleci/deploy.sh
            fi