version: 2
jobs:
  build:
    docker:
      - image: tiangolo/uwsgi-nginx-flask:python2.7
        environment:
          FLASK_CONFIG: testing
    steps:
      - deploy:
          name: Deploy Master to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              .circleci/deploy.sh
            fi